# Generated by Django 4.2.2 on 2023-06-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='university',
            name='country',
            field=models.CharField(default='default country', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='image',
            field=models.ImageField(upload_to='universities/media/universities/'),
        ),
    ]
