# Generated by Django 5.0.dev20230619181537 on 2023-06-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_images_alter_university_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default='default name', max_length=100),
            preserve_default=False,
        ),
    ]
