# Generated by Django 5.0.dev20230619181537 on 2023-06-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_images_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
