# Generated by Django 5.0.dev20230619181537 on 2023-06-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='cost',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='details',
            field=models.CharField(default='extra details', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='duration',
            field=models.CharField(default='0 years', max_length=100),
            preserve_default=False,
        ),
    ]
