# Generated by Django 5.0.dev20230619181537 on 2023-06-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.CharField(default='Ramdom description', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='domain',
            field=models.CharField(default='Random Domain', max_length=100),
            preserve_default=False,
        ),
    ]
