# Generated by Django 4.2.2 on 2023-06-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("start", "0002_remove_course_university_university_courses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestige",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="university", old_name="courses", new_name="course",
        ),
        migrations.RemoveField(model_name="course", name="level",),
        migrations.AddField(
            model_name="university",
            name="level",
            field=models.ForeignKey(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                to="start.level",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="university",
            name="prestige",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="start.prestige"
            ),
        ),
    ]
